import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=fileURLToPath(new URL('../../',import.meta.url)),out=root+'/qa/shared-fish-species',base=process.env.QA_BASE_URL||'http://127.0.0.1:4207/';
await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,channel:'chrome'}),ctx=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1}),page=await ctx.newPage(),errors=[],checks=[];
page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message)});
await page.route('**/pacifica-game.js',async route=>{const response=await route.fetch();await route.fulfill({response,body:await response.text()+'\nwindow.speciesQA={sim,start,openJournal,openShop,persist,updateUI,openCatch};'});});
await page.route('**/pixel-game.js?*',async route=>{const response=await route.fetch();await route.fulfill({response,body:await response.text()+'\nwindow.speciesQA={sim,start,openJournal,persist,updateUI,openCatch};'});});
const shot=name=>page.screenshot({path:out+'/'+name+'.png'}),state=()=>page.evaluate(()=>window.speciesQA.sim.state);
for(const scene of ['pacifica','half-moon-bay']){
 await page.addInitScript(scene=>{if(location.pathname.endsWith(scene+'.html')&&!sessionStorage.getItem(scene+'-qa-seeded')){sessionStorage.setItem(scene+'-qa-seeded','1');localStorage.setItem(scene+'-surf-save-v1',JSON.stringify({version:3,scene,credits:120,inventory:{sandcrab:12,squid:0,anchovy:0},upgrades:['surf_rod'],activeRod:'starter_rod',activeReel:'starter_reel',rodSupplies:{starter_rod:{id:'carolina_rig',condition:1,bait:{kind:'sandcrab',condition:1}},surf_rod:null},rigStock:{carolina_rig:[],fishfinder_rig:[]},catches:[{id:'surfperch',catchId:1,weightKg:.6},{id:'striped_bass',catchId:2,weightKg:2},{id:'halibut',catchId:3,weightKg:1.8,length:55}],pendingCatch:{id:'halibut',name:'加州比目鱼',catchId:4,weightKg:2},nextCatchId:5,stats:{caught:4,kept:3,released:0,sold:0,casts:4,missed:0}}));}},scene);
 await page.goto(base+scene+'.html');await page.locator('#start-btn').click();await page.locator('#catch-release').waitFor();
 assert.equal(await page.locator('#modal-title').textContent(),'加州大比目鱼');assert.match(await page.locator('#modal-content').textContent(),/California Halibut/);assert.match(await page.locator('#modal-content').textContent(),/Paralichthys californicus/);assert.match(await page.locator('#modal-content').textContent(),/未记录/);await shot(scene+'-old-catch');
 const credits=(await state()).credits;await page.locator('#catch-release').click();await page.locator('#journal-btn').click();assert.match(await page.locator('#modal-content').textContent(),/已放流/);assert.equal((await state()).credits,credits);await shot(scene+'-history-phone');
 await page.keyboard.press('Escape');assert.equal(await page.locator('#active-rod-name').textContent(),'入门岸钓竿');
 await page.reload();await page.locator('#start-btn').click();assert.equal((await state()).catchHistory.length,4);assert.equal((await state()).catches.length,3);await page.locator('#journal-btn').click();assert.match(await page.locator('#modal-content').textContent(),/已放流/);await page.keyboard.press('Escape');
 await page.evaluate(()=>{const q=window.speciesQA;Object.assign(q.sim.state.player,q.sim.shop.door);q.openShop();});await page.locator('#shop-sell').click();assert.equal((await state()).catches.length,0);assert.equal((await state()).catchHistory.length,4);await page.keyboard.press('Escape');await page.locator('#journal-btn').click();assert.match(await page.locator('#modal-content').textContent(),/已交付/);
 for(const [name,width,height] of [['small',320,568],['landscape',844,390],['desktop',1440,1000]]){await page.setViewportSize({width,height});await page.waitForTimeout(80);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await shot(scene+'-history-'+name);if(name==='small')console.log('LAYOUT',await page.evaluate(()=>{const b=document.querySelector('.balance').getBoundingClientRect(),c=document.querySelector('.close').getBoundingClientRect();return{balanceRight:b.right,closeLeft:c.left}}));}
 await page.keyboard.press('Escape');await page.setViewportSize({width:390,height:844});
 await page.evaluate(()=>{const q=window.speciesQA,s=q.sim.state;s.phase='walk';s.onPier=false;Object.assign(s.player,{x:2440,y:q.sim.world.shoreY(2440)+57});q.sim.rng=()=>.999;q.sim.cast();s.phase='bite';q.sim.strike();s.phase='landed';q.openCatch();q.persist();});
 const fish=(await state()).fish;assert.equal(fish.speciesId,'california_halibut');assert.ok(fish.length>0);assert.equal(fish.kg,fish.weightKg);assert.doesNotMatch(await page.locator('#modal-content').textContent(),/未记录/);await shot(scene+'-new-halibut');
 checks.push(scene+': v3 identity migration, pending unknown length preserved, release history survives reload, sold history retained, active rod title, four viewports, generated halibut shared mass/length');
}
await page.goto(base+'index.html');await page.locator('#start-btn').click();
await page.evaluate(()=>{const q=window.speciesQA,s=q.sim.state;s.fishState='landed';s.fish={name:'加州比目鱼',latin:'Paralichthys californicus',length:55,kg:1.8,catchId:'pending-sc'};s.fightTime=22;q.persist();});
await page.reload();await page.locator('#start-btn').click();await page.locator('#release-fish').waitFor();assert.equal(await page.locator('#modal-title').textContent(),'加州大比目鱼');assert.match(await page.locator('#modal-content').textContent(),/California Halibut/);await shot('santa-cruz-restored-catch');
await page.locator('#release-fish').click();const once=await state();assert.equal(once.catches.length,1);await page.reload();await page.locator('#start-btn').click();assert.equal((await state()).catches.length,1);assert.equal((await state()).profile.credits,once.profile.credits);assert.equal((await state()).fish,null);checks.push('Santa Cruz landed catch survives refresh, same halibut identity, release/reload has one record and no repeated reward');
assert.deepEqual(errors,[]);await fs.writeFile(out+'/browser-results.json',JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({checks,errors}));await browser.close();
