import test from 'node:test';import assert from 'node:assert/strict';
import {PixelHaptics} from '../dist/pixel-haptics.js';
function rig({supported=true,activated=true,saved='on',reject=false}={}){let time=0;const calls=[],values=new Map([['santa-cruz-haptics',saved]]),document={hidden:false},navigator={userActivation:{hasBeenActive:activated},...(supported?{vibrate:pattern=>{calls.push({time,pattern});return !reject;}}:{})};const h=new PixelHaptics({navigator,document,storage:{getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v)},now:()=>time});return{h,calls,document,navigator,values,tick:(ms=100)=>time+=ms};}
const s={mode:'boat',fishState:'fight',rodMount:'hand',reelMode:'brake',payoutRate:1,rodLoadN:16,lineSlackMeters:0,fishMotion:{headShake:0}};
test('bite is one distinct pattern and preempts a light feed tick',()=>{const r=rig();r.h.update({...s,fishState:'sinking',reelMode:'free'});r.h.update({...s,fishState:'bite'});assert.deepEqual(r.calls.map(c=>c.pattern),[6,0,[35,45,55]]);r.tick(1000);r.h.update({...s,fishState:'bite',payoutRate:0});assert.equal(r.calls.length,3);});
test('drag pulses track actual payout and stay bounded at 60 fps',()=>{const r=rig();for(let i=0;i<600;i++){r.h.update(s);r.tick(1000/60);}const pulses=r.calls.filter(c=>c.pattern);assert.ok(pulses.length>10&&pulses.length<40);assert.ok(pulses.every(c=>c.pattern<=27));for(let i=1;i<pulses.length;i++)assert.ok(pulses[i].time-pulses[i-1].time>=180);r.tick(1000);const count=r.calls.length;r.h.update({...s,payoutRate:0});assert.equal(r.calls.length,count,'spool stopped means no ratchet pulse');});
test('free feed is light and slower than running drag; slack and bottom overrun are silent',()=>{const r=rig();for(let i=0;i<60;i++){r.h.update({...s,fishState:'sinking',reelMode:'free'});r.tick(100);}assert.ok(r.calls.length>=8&&r.calls.length<=10);assert.ok(r.calls.every(c=>c.pattern===6));const count=r.calls.length;r.tick(1000);r.h.update({...s,fishState:'waiting',reelMode:'free',payoutRate:.05});r.h.update({...s,lineSlackMeters:2});assert.equal(r.calls.length,count);});
test('pause, background, loss of focus and disabled setting immediately stop cues',()=>{for(const reason of ['pause','hidden','focus','disable']){const r=rig();r.h.update(s);if(reason==='hidden')r.document.hidden=true;if(reason==='disable')r.h.toggle();r.h.update({...s,paused:reason==='pause'},{focused:reason!=='focus'});assert.equal(r.calls.at(-1).pattern,0);const count=r.calls.length;r.tick(1000);r.h.update({...s,paused:reason==='pause'},{focused:reason!=='focus'});assert.equal(r.calls.length,count);}});
test('unsupported, denied and not-yet-activated browsers never crash or pretend hardware worked',()=>{for(const settings of[{supported:false},{activated:false},{saved:'off'},{reject:true}]){const r=rig(settings);r.h.update({...s,fishState:'bite'});assert.equal(r.h.snapshot().acceptedPulses,0);}const r=rig();r.navigator.vibrate=()=>{throw Error('unavailable');};assert.doesNotThrow(()=>r.h.update({...s,fishState:'bite'}));assert.equal(r.h.supported,false);});
test('user preference persists independently from audio and bite cannot replay after pause',()=>{const r=rig();r.h.toggle();assert.equal(r.values.get('santa-cruz-haptics'),'off');r.h.toggle();r.h.update({...s,fishState:'bite',paused:true});r.h.update({...s,fishState:'bite',payoutRate:0});assert.equal(r.calls.length,0);});
