import test from 'node:test';
import assert from 'node:assert/strict';
import {fishTipSignal,stepRodTip,rodFlexPoint,rodAction} from '../dist/pixel-rod-response.js';
import {fightViewGeometry} from '../dist/pixel-fight-view.js';
import {getRodCurve,getFishingLine} from '../dist/pixel-rod-geometry.js';
const state=(kind='rockfish',kg=1,rod='rod')=>({fishState:'fight',fish:{fightKind:kind,kg,length:40},profile:{loadout:{rod}},fishFight:{energy:1},rodLoadN:5,rodBend:.4,lineSlackMeters:0,reelMode:'brake',time:0,rodElevation:45,rodAzimuth:70,rodMount:'hand'});
function sample(s,dt=1/60){const result=[];for(let t=0;t<5;t+=dt){s.time+=dt;s.rodTipMotion=stepRodTip(s,dt);result.push({...s.rodTipMotion});}return result;}
const rms=a=>Math.sqrt(a.reduce((n,p)=>n+p.y*p.y,0)/a.length);
test('fish species and size change tip signal frequency and force',()=>{const small=state('rockfish',.2),large=state('rockfish',5),bonito=state('bonito',5);assert.ok(fishTipSignal(small,1).frequency>fishTipSignal(large,1).frequency);assert.notEqual(fishTipSignal(large,1).frequency,fishTipSignal(bonito,1).frequency);assert.ok(rms(sample(large))>rms(sample(small))*2);assert.notDeepEqual(sample(state('lingcod',3)),sample(state('salmon',3)));});
test('fast light rod amplifies small fish while stronger moderate rod damps them',()=>{assert.ok(rms(sample(state('rockfish',.5,'rod_light')))>rms(sample(state('rockfish',.5,'rod_boat')))*1.4);assert.ok(rodFlexPoint(state('rockfish',1,'rod_light'),.5,100).shape<rodFlexPoint(state('rockfish',1,'rod_boat'),.5,100).shape);assert.equal(rodAction(state()).action,'moderate-fast');});
test('slack/free spool attenuate signal and exhausted fish move less',()=>{const normal=rms(sample(state('bonito',3)));assert.ok(rms(sample({...state('bonito',3),lineSlackMeters:2}))<normal*.01);assert.ok(rms(sample({...state('bonito',3),reelMode:'free'}))<normal*.2);assert.ok(rms(sample({...state('bonito',3),fishFight:{energy:.03}}))<normal*.5);});
test('bite has a signal; idle, escape and landing reset it; pause freezes it',()=>{const s={...state(),fishState:'bite',biteFish:{fightKind:'croaker',kg:.2,length:15}};assert.ok(rms(sample(s))>0);const before={...s.rodTipMotion};s.paused=true;assert.deepEqual(stepRodTip(s,.1),before);s.paused=false;for(const fishState of ['idle','waiting','sinking','landed','flight'])assert.deepEqual(stepRodTip({...s,fishState},.1),{x:0,y:0,vx:0,vy:0});});
test('tip integration is stable at phone frame rates and never mutates input',()=>{for(const dt of[1/120,1/60,.1,.25]){const values=sample(state('salmon',30,'rod_light'),dt);assert.ok(values.every(p=>Object.values(p).every(Number.isFinite)&&Math.abs(p.y)<=10&&Math.abs(p.x)<=6));}const s=state();Object.freeze(s);assert.doesNotThrow(()=>stepRodTip(s,.1));const a=sample(state(),1/60).at(-1),b=sample(state(),1/120).at(-1);assert.ok(Math.abs(a.y-b.y)<.25);});
test('first person and overhead tips move, but grip remains fixed and line stays attached',()=>{const s={...state(),rodTipMotion:{x:2,y:4},bobber:{x:4,z:3,height:-2},lureDepth:2};const plain={...s,rodTipMotion:null};for(const geometry of [s=>fightViewGeometry(390,844,s,{bottomInset:180}),s=>getRodCurve(s)]){const a=geometry(s),b=geometry(plain);assert.deepEqual(a.base,b.base);assert.notDeepEqual(a.tip,b.tip);}const g=fightViewGeometry(390,844,s);assert.strictEqual(g.line[0],g.tip);const rod=getRodCurve(s);assert.strictEqual(getFishingLine(s,rod).start,rod.tip);});
