import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
globalThis.fetch=async url=>new Response(await readFile(url));
const {PixelSimulation}=await import('../dist/pixel-sim.js');
const {restoreTripTime}=await import('../dist/pixel-day-cycle.js');
const oldDay='2026-09-28T13:00:00.000Z',later=()=>new Date('2026-12-24T23:00:00Z');
function savedTrip(){const s=new PixelSimulation({now:()=>new Date(oldDay),dailyWeather:true,weatherSeed:14});s.start();s.state.dayNumber=3;s.state.gameElapsed=4*3600+17*60+32.75;s.state.time=1400.25;s.state.elapsed=1400.25;s.state.clock=s.clock();return s.snapshot();}
test('continuation preserves exact time/date/weather across repeated reload and real-world date changes',()=>{let saved=savedTrip();saved.timeScale=5;for(let i=0;i<3;i++){const s=new PixelSimulation({saved,now:later});assert.equal(s.state.mode,'intro');assert.equal(s.state.clock,saved.clock);assert.equal(s.state.gameElapsed,saved.gameElapsed);s.start(true);assert.equal(s.state.dayNumber,3);assert.equal(s.state.dayStartAt,oldDay);assert.equal(s.state.gameElapsed,saved.gameElapsed);assert.deepEqual(s.state.dailyWeather,saved.dailyWeather);s.step(.1);assert.equal(s.state.gameElapsed,saved.gameElapsed+1);saved=s.snapshot();}});
test('legacy saves retain numeric elapsed time even without the day-cycle version marker',()=>{const saved=savedTrip();delete saved.dayCycleVersion;const s=new PixelSimulation({saved,now:later});s.start(true);assert.equal(s.state.dayStartAt,oldDay);assert.equal(s.state.gameElapsed,saved.gameElapsed);assert.equal(s.state.time,saved.time);assert.equal(s.state.elapsed,saved.elapsed);});
test('legacy clock-only saves recover display time; elapsed fallback uses saved speed, never the new speed',()=>{const saved=savedTrip();delete saved.dayCycleVersion;delete saved.gameElapsed;saved.clock='15:42:19';let s=new PixelSimulation({saved,now:later});s.start(true);assert.equal(s.state.clock,'15:42:19');delete saved.clock;saved.elapsed=900;saved.timeScale=2;s=new PixelSimulation({saved,now:later});s.start(true);assert.equal(s.state.gameElapsed,1800);assert.equal(s.state.clock,'06:30:00');});
test('fresh trips start at six; saved 18:00 triggers normal closure instead of rewinding',()=>{const fresh=new PixelSimulation({now:later});fresh.start();assert.equal(fresh.state.clock,'06:00:00');const saved=savedTrip();saved.gameElapsed=43200;const s=new PixelSimulation({saved,now:later});s.start(true);assert.equal(s.state.clock,'18:00:00');s.step(.1);assert.ok(s.state.dayTransition);assert.equal(s.state.gameElapsed,43200);});
test('malformed time fields recover safely without invalid date or NaN',()=>{const t=restoreTripTime({dayStartAt:'broken',dayNumber:-2,gameElapsed:NaN,elapsed:-3,clock:'99:99'},oldDay);assert.equal(t.dayStartAt,oldDay);assert.equal(t.gameElapsed,0);assert.equal(t.dayNumber,1);assert.equal(t.time,0);});
