import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
globalThis.fetch=async url=>new Response(await readFile(url));
const {PixelSimulation,HARBOR,FISHING_SPOTS}=await import('../dist/pixel-sim.js');
const {DAY_LENGTH_SECONDS,DAY_TRANSITION_SECONDS,TOW_FEE,dayTransitionVisual}=await import('../dist/pixel-day-cycle.js');
const {generateDailyWeather,dailyConditions,sampleDailyWater}=await import('../dist/pixel-daily-weather.js');
const {boatRenderPose,SKIFF_RACKS}=await import('../dist/pixel-boat-geometry.js');
const run=(s,seconds)=>{for(let t=0;t<seconds-1e-6;t+=.1)s.step(Math.min(.1,seconds-t));};
const begin=()=>{const s=new PixelSimulation({now:()=>new Date('2026-09-27T13:00:00Z'),dailyWeather:true,weatherSeed:42,patrolRng:()=>.99});s.start();return s;};
const expire=s=>{s.state.gameElapsed=DAY_LENGTH_SECONDS-.5;s.step(.1);};
function afloat(s){const p=FISHING_SPOTS[1];Object.assign(s.state,{mode:'boat',rentalPaid:true,launchStage:'afloat',boatX:p.x,boatZ:p.z});Object.assign(s.vessel,{x:p.x,z:p.z});}
test('daily weather is seeded, bounded, changes by day and varies smoothly during the day',()=>{for(let seed=0;seed<100;seed++){const a=generateDailyWeather(seed,1,9);assert.deepEqual(a,generateDailyWeather(seed,1,9));assert.notDeepEqual(a,generateDailyWeather(seed,2,9));for(const t of[0,18000,36000]){const c=dailyConditions(a,t,t/5),next=dailyConditions(a,t+.5,t/5+.1);assert.ok(c.waveHeight>0&&c.waveHeight<3);assert.ok(c.windKnots>0&&c.windKnots<30);assert.ok(Math.abs(next.windKnots-c.windKnots)<.3);assert.ok(Number.isFinite(sampleDailyWater(10,10,3,c)));}}});
test('wind affects drift, waves affect hull pitch/heave and rod/line environment',()=>{const s=begin();afloat(s);let heave=0,pitch=0;run(s,1);for(let i=0;i<300;i++){s.step(.1);heave=Math.max(heave,Math.abs(s.state.heave));pitch=Math.max(pitch,Math.abs(s.state.pitch));}assert.ok(heave>.02);assert.ok(pitch>.001);assert.ok(Math.hypot(s.vessel.vx,s.vessel.vz)>.03);assert.equal(s.rigEnvironment().waveHeight,s.conditions.waveHeight);});
test('late voyage costs 50 once, reverse-hoists, then resets rental at next 6am in ten seconds',()=>{const s=begin();afloat(s);s.state.profile.credits=80;const owned=[...s.state.profile.owned],weather=s.state.dailyWeather;expire(s);assert.equal(s.state.profile.credits,30);assert.equal(s.setThrottle(1),false);assert.equal(s.launchBoat().ok,false);assert.ok(s.state.dayTransition.late);run(s,3);assert.equal(s.state.launchStage,'raising');const pose=boatRenderPose(s.state,HARBOR);assert.ok(!pose.afloat);assert.ok(pose.lift>0);run(s,6.9);assert.ok(s.state.dayTransition);run(s,.1);assert.equal(s.state.dayTransition,null);assert.equal(s.state.dayNumber,2);assert.equal(s.state.dayStartAt,'2026-09-28T13:00:00.000Z');assert.equal(s.state.clock,'06:00:00');assert.equal(s.state.launchStage,'stored');assert.equal(s.state.rentalPaid,false);assert.deepEqual(s.state.profile.owned,owned);assert.notDeepEqual(s.state.dailyWeather,weather);assert.equal(s.state.profile.credits,30);assert.equal(s.state.mode,'walk');assert.equal(DAY_TRANSITION_SECONDS,10);});
test('returning ashore before close has no penalty and stores boat; interruption cannot double-charge',()=>{const shore=begin();Object.assign(shore.state,{rentalPaid:true,launchStage:'afloat'});expire(shore);assert.equal(shore.state.dayTransition.late,false);run(shore,10);assert.equal(shore.state.profile.credits,100);assert.equal(shore.state.launchStage,'stored');const s=begin();afloat(s);s.state.profile.credits=12;expire(s);assert.equal(s.state.profile.credits,0);assert.equal(s.state.profile.towDebt,TOW_FEE-12);run(s,3);const resumed=new PixelSimulation({saved:s.snapshot()});resumed.start(true);run(resumed,10);assert.equal(resumed.state.profile.towDebt,38);resumed.state.profile.credits=20;resumed.payTowDebt();assert.equal(resumed.state.profile.credits,0);assert.equal(resumed.state.profile.towDebt,18);});
test('pause freezes transition, stored boat matches rack and night/dawn phases remain bounded',()=>{const s=begin();expire(s);s.pause(true);run(s,15);assert.equal(s.state.dayTransition.elapsed,0);s.pause(false);run(s,10);const pose=boatRenderPose(s.state,HARBOR);assert.equal(pose.x,SKIFF_RACKS[0].x);for(let t=0;t<=10;t+=.1){const v=dayTransitionVisual({elapsed:t});assert.ok(v.shade>=0&&v.shade<=1);}assert.equal(dayTransitionVisual({elapsed:6.5}).phase,'夜幕降临');assert.equal(dayTransitionVisual({elapsed:9}).phase,'次日 · 06:00');});
test('forced return still checks undersized fish and never converts them to credits',()=>{const s=begin();afloat(s);s.state.catches.push({catchId:'illegal-day',speciesId:'california_halibut',name:'加州大比目鱼',latin:'Paralichthys californicus',length:40,kg:1,kept:true,caughtAt:s.captureTimestamp(),caughtGPS:{lat:36.9505,lon:-122.0288},hookCount:1,landingNetDiameterInches:20});expire(s);run(s,10);assert.equal(s.state.catches[0].confiscated,true);assert.equal(s.state.catches[0].reward,0);assert.equal(s.state.profile.credits,0);assert.equal(s.state.profile.fineDebt,50);});
