import test from 'node:test';import assert from 'node:assert/strict';
import {fightPumpControl} from '../dist/pixel-fight-pump.js';
import {stepFishingLine,rodTipPosition} from '../dist/pixel-fishing-physics.js';
function make(kg=4){const s={fishState:'fight',fish:{kg},rig:'bottom',boatX:0,boatZ:0,heading:0,rodElevation:24,rodAzimuth:70,rodMount:'hand',reelMode:'brake',drag:.7,crankRate:0,pumpHeight:0,rodLoadN:0,rodBend:0,paidLineMeters:15};const tip=rodTipPosition(s);s.bobber={x:tip.x,z:tip.z,height:tip.height-15};s.lureDepth=-s.bobber.height;return s;}
function step(s,phase,seconds,{pull=8,area=.045,dt=.05}={}){for(let t=0;t<seconds-dt/2;t+=dt){s.fishPullN=pull;Object.assign(s,fightPumpControl(s,phase));const before=s.paidLineMeters;Object.assign(s,stepFishingLine(s,{dt,environment:{bottomDepth:30},fishPullN:pull,fishMotion:{bodyDragArea:area}}));assert.ok(Math.abs(s.paidLineMeters-before-(s.payoutRate-s.retrieveRate)*dt)<1e-8);assert.equal(s.rodAzimuth,70);}return s;}
test('hold produces one bounded lift; release lowers and winds without inventing line gain',()=>{const s=make(),depth=s.lureDepth,paid=s.paidLineMeters;step(s,'lift',7);assert.ok(s.rodElevation>60);assert.equal(s.paidLineMeters,paid);assert.equal(s.crankRate,0);const high=s.lureDepth;step(s,'lift',3);assert.ok(Math.abs(s.lureDepth-high)<.03);step(s,'recover',4);assert.ok(s.rodElevation<=24.3);assert.ok(s.paidLineMeters<paid-.5);assert.ok(s.lureDepth<depth-.5);assert.equal(s.crankRate,0);});
test('large resistant fish slow lifting; surging fish can lower a held rod and slip drag',()=>{const small=make(.5),large=make(9);step(small,'lift',1,{pull:2,area:.004});step(large,'lift',1,{pull:15,area:.1});assert.ok(small.rodElevation>large.rodElevation+4);assert.ok(large.rodBend>small.rodBend);step(large,'lift',5,{pull:4,area:.1});const high=large.rodElevation;step(large,'lift',1,{pull:45,area:.1});assert.ok(large.rodElevation<high);assert.ok(large.payoutRate>0);});
test('idle, cancellation, pause and mounted rods do not start automatic winding',()=>{for(const patch of [{},{paused:true},{rodMount:'port'},{fishState:'idle'}]){const s={...make(),...patch};const r=fightPumpControl(s,'idle');assert.equal(r.fightPumpPhase,'idle');assert.equal(r.rodTargetElevation,null);assert.equal(r.crankRate,undefined);}});
test('pump animation remains consistent at mobile frame rates',()=>{const result=[];for(const dt of [1/60,.05,.1]){const s=make();for(let n=0;n<3;n++){step(s,'lift',5,{dt});step(s,'recover',4,{dt});}result.push(s.lureDepth);}assert.ok(Math.max(...result)-Math.min(...result)<.35);});

test('a completed recovery releases the reel for manual winding',()=>{const s=make();s.lineSlackMeters=0;const result=fightPumpControl(s,'recover',{manualCrank:.8});assert.equal(result.fightPumpPhase,'idle');assert.equal(result.crankRate,.8);assert.equal(result.reeling,true);});
