import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
globalThis.fetch=async url=>new Response(await readFile(url));
const {PixelSimulation,FISHING_SPOTS}=await import('../dist/pixel-sim.js');
const {createVesselState,stepVessel}=await import('../dist/vessel-physics.js');
const {createStability,rightingArm}=await import('../dist/pixel-stability.js');
const {sampleDailyWater}=await import('../dist/pixel-daily-weather.js');
const {boatActions}=await import('../dist/pixel-boat-actions.js');
function sea({height=.4,period=6,heading=0,water=0,payload=0,dt=.05,seconds=180,bailing=false,scale=1}={}){const v=createVesselState({heading});v.stability=createStability({waterLitres:water});for(let t=0;t<seconds-1e-6;t+=dt){stepVessel(v,{dt:dt*scale,motionTimeScale:1/scale,time:t+dt,stability:true,bailing,payloadKg:payload,floodKg:v.stability.waterLitres,sampleWater:(x,z,t)=>sampleDailyWater(x,z,t,{swellHeight:height,period,waveDirection:44})});if(v.stability.capsized)break;}return v;}
function begin(){const sim=new PixelSimulation({patrolRng:()=>.99});sim.start();const p=FISHING_SPOTS[1];Object.assign(sim.state,{mode:'boat',rentalPaid:true,launchStage:'afloat',boatX:p.x,boatZ:p.z});Object.assign(sim.vessel,{x:p.x,z:p.z});return sim;}
const run=(sim,seconds)=>{for(let t=0;t<seconds-1e-6;t+=.1)sim.step(.1);};
test('calm and 3m long-period swell do not trigger height-based capsize',()=>{for(const opts of [{},{height:3,period:15}]){const v=sea(opts);assert.equal(v.stability.capsized,false);assert.equal(v.stability.waterLitres,0);}});
test('steep transverse sea ships water then overturns; head sea has less roll',()=>{const beam=sea({height:3,period:2.5}),head=sea({height:3,period:2.5,heading:Math.PI/2});assert.ok(beam.stability.capsized);assert.ok(beam.stability.waterLitres>100);assert.ok(Math.abs(head.roll)<Math.abs(beam.roll));});
test('wet loaded hull has less righting arm and large angles lose stability',()=>{assert.ok(rightingArm(.4,150,60)<rightingArm(.4,0,0));assert.ok(rightingArm(2.2)<0);assert.ok(sea({height:2.5,period:3,payload:100}).stability.waterLitres>sea({height:2.5,period:3}).stability.waterLitres);});
test('bailing removes water in real seconds, travel compression does not accelerate stability',()=>{const a=sea({height:0,water:70,bailing:true,seconds:10}),b=sea({height:0,water:70,bailing:true,seconds:10,scale:2});assert.ok(Math.abs(a.stability.waterLitres-56)<.02);assert.ok(Math.abs(a.stability.waterLitres-b.stability.waterLitres)<.02);const c=sea({height:2.5,period:3,seconds:60,dt:.025}),d=sea({height:2.5,period:3,seconds:60,dt:.1});assert.ok(Math.abs(c.stability.waterLitres-d.stability.waterLitres)<2);});
test('bailing stops propulsion and reel, pause and reload preserve flooded hull',()=>{const sim=begin();sim.state.stability.waterLitres=80;sim.state.fishState='waiting';sim.state.reeling=true;sim.state.throttle=1;assert.ok(sim.setBailing(true));assert.equal(sim.state.rodMount,'port');assert.equal(sim.state.throttle,0);assert.equal(boatActions(sim.state).reel,false);sim.step(.1,{reel:2,throttle:1});assert.equal(sim.state.reeling,false);assert.equal(sim.state.throttle,0);sim.pause(true);run(sim,3);const wet=sim.state.stability.waterLitres;assert.ok(wet>79);const restored=new PixelSimulation({saved:sim.snapshot()});restored.start(true);assert.equal(restored.state.stability.waterLitres,wet);assert.equal(restored.state.bailing,false);});
test('capsize loses all gear and unsettled cargo, charges once across reload and daily close',()=>{const sim=begin(),s=sim.state,owned=[...s.profile.owned];s.profile.credits=12;s.catches=[{kept:true,settled:true,catchId:'old',reward:10},{kept:true,settled:false,catchId:'trip',reward:8}];s.fishState='waiting';sim.beginCapsize();assert.equal(s.profile.credits,0);assert.equal(s.profile.towDebt,38);assert.equal(s.catches[0].reward,10);assert.ok(s.catches[1].lost);assert.deepEqual(s.profile.rodSupplies,{});assert.deepEqual(s.profile.owned,[]);assert.ok(owned.length>0);sim.beginCapsize();sim.beginDayEnd();assert.equal(s.profile.towDebt,38);assert.equal(s.dayTransition,null);const restored=new PixelSimulation({saved:sim.snapshot()});restored.start(true);assert.ok(restored.state.capsize);run(restored,6.1);assert.ok(restored.state.dayTransition.rescue);restored.beginDayEnd();run(restored,10);assert.equal(restored.state.clock,'06:00:00');assert.equal(restored.state.profile.towDebt,38);assert.equal(restored.state.launchStage,'stored');assert.equal(restored.state.stability.waterLitres,0);assert.ok(restored.state.lastDay.rescue);assert.deepEqual(restored.state.profile.rodSupplies,{});assert.deepEqual(restored.state.profile.owned,[]);});
test('automatic motor has no immunity; irreversible flood state triggers rescue through simulation',()=>{const sim=begin();sim.state.motorMode='hold';sim.state.stability.waterLitres=410;run(sim,1);assert.ok(sim.state.capsize);assert.equal(sim.state.motorMode,'off');assert.equal(sim.setBailing(true),false);assert.equal(sim.rescue().ok,false);});
