import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
globalThis.fetch=async url=>new Response(await readFile(url));
const {PixelSimulation,HARBOR}=await import('../dist/pixel-sim.js');
const run=(sim,n)=>{for(let t=0;t<n-1e-7;t+=.1)sim.step(.1);};
function begin(){const sim=new PixelSimulation({patrolRng:()=>.99});sim.start();Object.assign(sim.state,{mode:'boat',rentalPaid:true,launchStage:'afloat'});return sim;}
test('owned but not worn PFD causes hospital admission and separate one-time medical bill',()=>{const sim=begin(),s=sim.state;s.profile.credits=500;assert.ok(sim.equip('pfd').ok);assert.equal(s.pfd,false);assert.ok(s.profile.owned.includes('pfd'));sim.equip('net');assert.equal(s.pfd,false);sim.beginCapsize();assert.equal(s.profile.credits,200);assert.ok(s.capsize.hospital);assert.equal(s.capsize.hospitalFee,250);assert.equal(s.capsize.worePfd,false);assert.deepEqual(s.packed,[]);assert.deepEqual(s.profile.owned,[]);sim.beginCapsize();assert.equal(s.profile.credits,200);run(sim,8);assert.ok(s.capsize.elapsed>=7.9);assert.equal(s.dayTransition,null);const resumed=new PixelSimulation({saved:sim.snapshot()});resumed.start(true);run(resumed,6.1);assert.ok(resumed.state.dayTransition.hospital);run(resumed,10);assert.equal(resumed.state.profile.credits,200);assert.equal(resumed.state.lastDay.hospitalFee,250);assert.equal(resumed.state.clock,'06:00:00');});
test('worn PFD protects from hospital, but every owned item and spare is lost including stowed electronics',()=>{const sim=begin(),s=sim.state;s.profile.owned.push('gps','rod_electric');s.profile.credits=500;sim.beginCapsize();assert.equal(s.profile.credits,450);assert.equal(s.capsize.hospital,false);assert.equal(s.capsize.worePfd,true);assert.deepEqual(s.profile.owned,[]);assert.deepEqual(s.profile.rodLoadouts,{});assert.ok(Object.values(s.profile.stock).every(v=>v===0));assert.ok(Object.values(s.profile.rigStock).every(v=>v.length===0));run(sim,16.1);const resumed=new PixelSimulation({saved:sim.snapshot()});resumed.start(true);resumed.packStarter();assert.deepEqual(resumed.state.profile.owned,[]);assert.deepEqual(resumed.state.packed,[]);assert.equal(resumed.state.pfd,false);assert.equal(resumed.stats.hasRod,false);});
test('hospital shortfall persists and later earnings repay without double charging',()=>{const sim=begin();sim.equip('pfd');sim.state.profile.credits=20;sim.beginCapsize();assert.equal(sim.state.profile.towDebt,30);assert.equal(sim.state.profile.medicalDebt,250);const resumed=new PixelSimulation({saved:sim.snapshot()});resumed.start(true);run(resumed,24.1);assert.equal(resumed.state.profile.medicalDebt,250);resumed.state.profile.credits=100;resumed.payTowDebt();assert.equal(resumed.state.profile.credits,0);assert.equal(resumed.state.profile.towDebt,0);assert.equal(resumed.state.profile.medicalDebt,180);});
test('lost starter gear can be bought at the shop and reactivated without recreating free stock',()=>{const sim=begin();sim.state.profile.credits=500;sim.beginCapsize();run(sim,16.1);Object.assign(sim.state,{playerX:HARBOR.counterX,playerZ:HARBOR.counterZ});for(const id of ['pfd','rod','bait','tackle']){assert.ok(sim.buyGear(id).ok,id);assert.ok(sim.equip(id).ok,id);}assert.equal(sim.state.pfd,true);assert.ok(sim.stats.hasRod);assert.equal(sim.state.profile.stock.squid,12);assert.equal(sim.state.profile.rigStock.bottom.length,1);const r=new PixelSimulation({saved:sim.snapshot()});r.start(true);assert.deepEqual(r.state.profile.owned,sim.state.profile.owned);assert.equal(r.state.profile.stock.squid,12);});
test('legacy implicit PFD migrates to worn once; deliberate removal persists',()=>{const sim=begin(),old=sim.snapshot();delete old.pfdStateVersion;old.packed=old.packed.filter(id=>id!=='pfd');old.pfd=true;let r=new PixelSimulation({saved:old});r.start(true);assert.equal(r.state.pfd,true);r.equip('pfd');r=new PixelSimulation({saved:r.snapshot()});r.start(true);assert.equal(r.state.pfd,false);assert.equal(r.hasGear('pfd'),false);});
